spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leadnews_admin?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

swagger2:
  enable: true
#开启增强功能
knife4j:
  enable: true

logging:
  #引入日志配置文件，果你的名字是logback-spring.xml不用引入，会自动寻找
  config: classpath:logback-spring.xml

package:
  name: com.dwyinyuan
  author: 公众号:笛舞音缘
  moduleName: code

# 访问地址   localhost:8081/generator/generate?tableNames=ad_channel  自行替换表名，多张用逗号隔开
